# Generated by Django 6.0.7 on 2026-07-22 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('projects', '0002_project_progress_projectactivity_projectexpense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='crm.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='category',
            field=models.CharField(choices=[('material', 'Materials'), ('labor', 'Labor'), ('fuel', 'Fuel'), ('transport', 'Transport'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='projectmilestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=30),
        ),
    ]
