# Generated by Django 6.0.7 on 2026-07-22 15:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.PositiveIntegerField(default=0, help_text='Project completion percentage'),
        ),
        migrations.AlterField(
            model_name='projectactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='category',
            field=models.CharField(choices=[('material', 'Materials'), ('labor', 'Labor'), ('fuel', 'Fuel'), ('transport', 'Transport'), ('equipment', 'Equipment'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
