# Generated by Django 5.2.16 on 2026-07-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('excavator', 'Excavator'), ('backhoe', 'Backhoe Loader'), ('roller', 'Roller'), ('grader', 'Motor Grader'), ('bulldozer', 'Bulldozer'), ('loader', 'Wheel Loader'), ('forklift', 'Forklift'), ('crane', 'Crane'), ('lowbed', 'Lowbed'), ('dumptruck', 'Dump Truck'), ('other', 'Other')], max_length=30)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('engine_number', models.CharField(blank=True, max_length=150)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('current_site', models.CharField(blank=True, max_length=150)),
                ('operator', models.CharField(blank=True, max_length=150)),
                ('running_hours', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('working', 'Working'), ('maintenance', 'Maintenance'), ('breakdown', 'Breakdown'), ('rented', 'Rented'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['equipment_id'],
            },
        ),
    ]
