# Generated by Django 5.2.16 on 2026-07-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='equipment_id',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='purchase_cost',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='running_hours',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='hour_meter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='engine_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='operator',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('working', 'Working'), ('rented', 'On Rental'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
