# Generated by Django 6.0.7 on 2026-07-14 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipmentcategory_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdocument',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentimage',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='equipmentlocation',
            name='equipment',
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipment'},
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='equipment_code',
            new_name='asset_number',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='notes',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='year',
            new_name='manufacture_year',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='average_consumption',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='current_operator',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='current_site',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='fuel_capacity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='insurance_company',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='insurance_policy',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_service_hours',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='next_service_hours',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='odometer',
        ),
        migrations.RemoveField(
            model_name='equipmentcategory',
            name='code',
        ),
        migrations.AddField(
            model_name='equipment',
            name='current_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='equipment',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='equipment',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='weekly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.equipmentcategory'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Other', 'Other')], default='Diesel', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='hour_meter',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='ownership',
            field=models.CharField(choices=[('Company', 'Company'), ('Leased', 'Leased'), ('Hired', 'Hired')], default='Company', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Working', 'Working'), ('Rented', 'Rented'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='Available', max_length=30),
        ),
        migrations.DeleteModel(
            name='EquipmentAssignment',
        ),
        migrations.DeleteModel(
            name='EquipmentDocument',
        ),
        migrations.DeleteModel(
            name='EquipmentImage',
        ),
        migrations.DeleteModel(
            name='EquipmentLocation',
        ),
    ]
