# Generated by Django 6.0.7 on 2026-07-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('management', 'Management'), ('finance', 'Finance'), ('engineering', 'Engineering'), ('projects', 'Projects'), ('equipment', 'Equipment'), ('fuel', 'Fuel Management'), ('real_estate', 'Real Estate'), ('administration', 'Administration')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Managing Director'), ('director', 'Director'), ('manager', 'Manager'), ('secretary', 'Secretary')], default='secretary', max_length=20),
        ),
    ]
