# Generated by Django 6.0.7 on 2026-07-15 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuelrecord',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Fuel Record', 'verbose_name_plural': 'Fuel Records'},
        ),
        migrations.AddField(
            model_name='fuelrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='meter_reading',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Mobile Money', 'Mobile Money'), ('Credit', 'Credit')], default='Cash', max_length=30),
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='project',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fuelrecord',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
    ]
