# Generated by Django 6.0.7 on 2026-07-22 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('project_updates', models.BooleanField(default=True)),
                ('payment_alerts', models.BooleanField(default=True)),
                ('equipment_alerts', models.BooleanField(default=True)),
                ('maintenance_alerts', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Setting',
                'verbose_name_plural': 'Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='RLB-AM EMS', max_length=100)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_dark_mode', models.BooleanField(default=False)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('items_per_page', models.PositiveIntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Preference',
                'verbose_name_plural': 'System Preferences',
            },
        ),
        migrations.DeleteModel(
            name='NotificationSettings',
        ),
        migrations.DeleteModel(
            name='SystemSettings',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='description',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='country',
            field=models.CharField(default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='short_name',
            field=models.CharField(default='RLB-AM', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
